name: Deploy ISer Public API
# run-name: ${{ github.workflow }} - ${{ github.ref }} - ${{ github.sha }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    env:
      SERVER_LOCAL_PATH: ~/servers/iser-public-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Use Node.js 18
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      - name: Install dependencies
        run: pnpm install
        # --no-frozen-lockfile 默认配置

      - name: Build project
        run: pnpm run build

      # - name: Remove previous build artifacts
      #   run: rm -rf ${{ env.SERVER_LOCAL_PATH }}/*

      - name: Move product
        run: |
          mkdir -p ${{ env.SERVER_LOCAL_PATH }}/logs
          cp -r ./dist/* ${{ env.SERVER_LOCAL_PATH }}/
          cp ./package.json ${{ env.SERVER_LOCAL_PATH }}/
          cp ./ecosystem.config.js ${{ env.SERVER_LOCAL_PATH }}/

      - name: Stop existing PM2 process
        run: pm2 stop IserPublicApi || true
        continue-on-error: true

      - name: Deploy project
        run: |
          cd ${{ env.SERVER_LOCAL_PATH }}
          pm2 start ecosystem.config.js --env production
          pm2 save
        # pm2 start ${{ env.SERVER_LOCAL_PATH }}/main.js --env production # 这个也可行
        # startOrRestart 导致 config undefined
        # pm2 startOrRestart ${{ env.SERVER_LOCAL_PATH }}/main.js --env production
        env:
          SERVER_PORT: 6990
          AUTHORITY_API_KEY: ${{ secrets.AUTHORITY_API_KEY }}
          WXWORK_WEBHOOK_URL: https://qyapi.weixin.qq.com/cgi-bin/webhook/send
          QWEATHER_LOCATION: ${{ secrets.QWEATHER_LOCATION }}
          QWEATHER_API_KEY: ${{ secrets.QWEATHER_API_KEY }}
          QWEATHER_API_HOST: ${{ secrets.QWEATHER_API_HOST }}
          GAMELOG_BASEURL: ${{ secrets.GAMELOG_BASEURL }}
          GAMELOG_GENSHINLOGSURL: ${{ secrets.GAMELOG_GENSHINLOGSURL }}
          GAMELOG_STARRAILLOGSURL: ${{ secrets.GAMELOG_STARRAILLOGSURL }}
      - name: Clean up
        run: rm -rf node_modules